version: 2

models:
  - name: transform
    description: "Dataset des trajets en taxi jaune de New York au cours de l'année 2024."
    columns:
      - name: tpep_pickup_datetime
        description: "La date et l'heure auxquelles le compteur a été activé."
        tests:
          - not_null

      - name: tpep_dropoff_datetime
        description: "La date et l'heure auxquelles le compteur a été désactivé."
        tests:
          - not_null

      - name: trip_duration_minutes
        description: "La durée du trajet en minutes."
        tests:
          - not_null

      - name: trip_distance
        description: "La distance du trajet en miles."
        tests:
          - not_null

      - name: passenger_count
        description: "Le nombre de passagers dans le véhicule."
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: BIGINT

      - name: payment_method
        description: "Méthode de paiement traduite."
        tests:
          - not_null
          - accepted_values:
              values: ["Credit card", "Cash"]

      - name: store_and_fwd_flag
        description: "Indique si l’enregistrement du trajet a été stocké en mémoire du véhicule."
        tests:
          - not_null
          - accepted_values:
              values: ["N"]

      - name: PULocationID
        description: "La zone taxi où le trajet a commencé."
        tests:
          - not_null

      - name: DOLocationID
        description: "La zone taxi où le trajet s’est terminé."
        tests:
          - not_null

      - name: fare_amount
        description: "Le tarif temps-distance calculé par le compteur."
        tests:
          - not_null

      - name: total_amount
        description: "Le montant total facturé au passager."
        tests:
          - not_null

      - name: tip_amount
        description: "Le montant du pourboire."
        tests:
          - not_null

      - name: tolls_amount
        description: "Le montant des péages payés pendant le trajet."
        tests:
          - not_null

      - name: improvement_surcharge
        description: "La surcharge d’amélioration payée pendant le trajet."
        tests:
          - not_null

      - name: congestion_surcharge
        description: "La surcharge de congestion payée pendant le trajet."
        tests:
          - not_null

      - name: extra
        description: "Les frais supplémentaires payés pendant le trajet."
        tests:
          - not_null  

      - name: mta_tax
        description: "La taxe MTA payée pendant le trajet."
        tests:
          - not_null 

      - name: Airport_fee
        description: "Les frais d’aéroport payés pendant le trajet."
        tests:
          - not_null  
