version: 2

models:
  - name: transform
    description: "Dataset des trajets en taxi jaune de New York au cours de l'année 2024."
    columns:
      - name: tpep_pickup_datetime
        description: "The date and time when the meter was engaged."
        tests:
          - not_null

      - name: tpep_dropoff_datetime
        description: "The date and time when the meter was disengaged."
        tests:
          - not_null

      - name: trip_duration_minutes
        description: "The duration of the trip in minutes."
        tests:
          - not_null

      - name: trip_distance
        description: "The trip distance in miles."
        tests:
          - not_null

      - name: passenger_count
        description: "The number of passengers in the vehicle."
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: BIGINT

      - name: payment_method
        description: "Translated payment method."
        tests:
          - not_null
          - accepted_values:
              values: ["Credit card", "Cash"]

      - name: store_and_fwd_flag
        description: "Indicates whether the trip record was stored in vehicle memory."
        tests:
          - not_null
          - accepted_values:
              values: ["N"]
      - name: PULocationID
        description: "The taxi zone where the trip started."
        tests:
          - not_null

      - name: DOLocationID
        description: "The taxi zone where the trip ended."
        tests:
          - not_null

      - name: fare_amount
        description: "The time-and-distance fare calculated by the meter."
        tests:
          - not_null

      - name: total_amount
        description: "The total amount charged to the passenger."
        tests:
          - not_null

      - name: tip_amount
        description: "The tip amount."
        tests:
          - not_null

      - name: tolls_amount
        description: "The amount of tolls paid in trip."
        tests:
          - not_null

      - name: improvement_surcharge
        description: "The improvement surcharge paid in trip."
        tests:
          - not_null

      - name: congestion_surcharge
        description: "The congestion surcharge paid in trip."
        tests:
          - not_null

      - name: extra
        description: "The extra paid in trip."
        tests:
          - not_null  

      - name: mta_tax
        description: "The MTA paid in trip."
        tests:
          - not_null 

      - name: Airport_fee
        description: "The airport fee paid in trip."
        tests:
          - not_null         
